version: 2.1
jobs:
  test:
    docker: 
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npm install
      - run: sudo npm install -g truffle
      - run: truffle test

  deploy_ropsten:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: ./auto/deploy
      - store_artifacts:
          path: /deployed_address.txt

workflows:
  test-and-deploy:
    jobs:
      - test
      - deploy_ropsten:
          requires:
            - test
